api:
  url: https://staticman3.herokuapp.com/v2/entry/github/your-username/your-repository/master/comments
  branch: master
fields:
  - name: name
    label: Your Name
    placeholder: John Doe
    type: text
    required: true
  - name: email
    label: Email
    placeholder: john.doe@example.com
    type: email
    required: false
  - name: message
    label: Your Comment
    placeholder: Leave a comment
    type: textarea
    required: true
