name: 自动生成并部署 Jekyll 到 GitHub Pages

on:
  push:
    branches: ["main"]  # 监听 `main` 分支的推送，自动触发工作流
  workflow_dispatch:  # 支持手动触发工作流

permissions:
  contents: write  # 读取权限
  pages: write  # 写入 GitHub Pages 权限
  id-token: write  # 可选，根据需要

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 预部署任务，确保依赖和字体准备就绪
  work:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 更新软件包列表并安装依赖
        run: |
          sudo mkdir -p /usr/share/fonts/truetype/chinese

      - name: 复制字体到系统
        run: |
          sudo cp /home/runner/work/AliceAuto.github.io/AliceAuto.github.io/刷题模块/脚本集/data/fonts/msyh.ttf /usr/share/fonts/truetype/chinese

      - name: 更新字体缓存
        run: |
          sudo fc-cache -fv
          fc-list :lang=zh

      - name: 禁用字体缓存
        run: |
          export FONTCONFIG_PATH=/dev/null
          fc-cache -fv

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r ./刷题模块/脚本集/requirements.txt

      - name: 运行自定义 Python 脚本
        run: |
          cd ./刷题模块/
          python 脚本集/Scripts/DataVisualization/src/main.py  # 运行脚本生成文件

      - name: 检查是否有新生成的文件
        run: |
          echo "检查哪些文件被修改或新增："
          git status  # 查看当前工作区的状态
          git diff  # 查看文件差异，确认是否有新的文件修改

      - name: 设置 Git 用户信息
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 提交生成的文件
        run: |
          # 设置 Git 用户信息
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 添加所有修改过的文件
          git add .

          # 检查是否有文件差异（如果没有差异，不提交）
          git diff --cached --quiet || (git commit -m "自动提交生成的文件" && git push origin main)

          # 如果没有更改，git diff --cached --quiet 会使得提交跳过
          echo "提交完成（如果有更改的话）。"

  # 构建与部署任务
  build:
    runs-on: ubuntu-latest
    needs: work  # 确保 build 步骤在 work 完成后执行

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 拉取最新的远程仓库内容
        run: |
          git pull origin main  # 拉取最新的远程仓库内容

      - name: 清理旧的页面缓存
        run: |
          echo "清理旧的页面缓存..."
          rm -rf _site  # 删除 _site 目录，清理缓存

      - name: 设置 Pages
        uses: actions/configure-pages@v5

      - name: 使用 Jekyll 构建网站
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./  # 确保源目录是正确的
          destination: ./_site  # 确保构建目录是 _site

      - name: 列出生成的文件
        run: |
          echo "列出 _site 目录中的内容："
          ls -R ./ # 列出 _site 目录中的内容，确保其生成
          
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3

      - name: 配置 GitHub 用户信息
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 创建新的 gh-pages 分支
        run: |
          git checkout -B gh-pages  # 创建并切换到 gh-pages 分支
          git reset --hard
          git init  # 重新初始化 Git 仓库，确保有 .git 目录

      - name: 列出当前工作目录
        run: |
          echo "当前工作目录："
          pwd  # 输出当前工作目录
          ls -R  # 列出当前工作目录下的所有文件，确保路径正确

      - name: 使用 Personal Access Token 推送
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/AliceAuto/AliceAuto.github.io.git
          git push --force --set-upstream origin gh-pages
