name: 自动生成并部署 Jekyll 到 GitHub Pages

on:
  push:
    branches: ["main"]  # 监听 `main` 分支的推送，自动触发工作流
  workflow_dispatch:  # 支持手动触发工作流

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 预部署任务，确保依赖和字体准备就绪
  work:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 更新软件包列表并安装依赖
        run: |
          sudo mkdir -p /usr/share/fonts/truetype/chinese

      - name: 复制字体到系统
        run: |
          sudo cp /home/runner/work/AliceAuto.github.io/AliceAuto.github.io/刷题模块/脚本集/data/fonts/msyh.ttf /usr/share/fonts/truetype/chinese

      - name: 更新字体缓存
        run: |
          sudo fc-cache -fv
          fc-list :lang=zh

      - name: 禁用字体缓存
        run: |
          export FONTCONFIG_PATH=/dev/null
          fc-cache -fv

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r ./刷题模块/脚本集/requirements.txt

      - name: 运行自定义 Python 脚本
        run: |
          cd ./刷题模块/
          python 脚本集/Scripts/DataVisualization/src/main.py

  # Jekyll 网站构建任务
  build:
    runs-on: ubuntu-latest
    needs: work
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 Pages
        uses: actions/configure-pages@v5

      - name: 使用 Jekyll 构建网站
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./  # Jekyll 源文件所在的目录
          destination: ./_site  # 输出目录

      - name: 列出生成的文件
        run: |
          ls -R ./  # 列出当前目录下的所有文件，确认是否有 _site 目录

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3

  # 部署任务到 GitHub Pages
  deploy:
    environment:
      name: github-pages

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 配置 GitHub 用户信息
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 创建新的 gh-pages 分支
        run: |
          git checkout --orphan gh-pages  # 创建一个孤立的分支 gh-pages
          git reset --hard
          git init  # 重新初始化 Git 仓库，确保有 .git 目录

      - name: 列出生成的文件
        run: |
          ls -R ./  # 列出当前目录下的所有文件，确认是否有 _site 目录

      - name: 确保 _site 目录存在
        run: |
          if [ -d "./_site" ]; then
            echo "_site 目录已生成"
          else
            echo "未生成 _site 目录，请检查构建步骤。" && exit 1
          fi

      - name: 将生成的静态内容复制到根目录
        run: |
          if [ -d "./_site" ]; then
            cp -r ./_site/* .  # 如果 _site 存在，则复制文件
          else
            echo "_site 目录未生成，请检查构建步骤。" && exit 1
          fi

      - name: 提交并推送到 gh-pages 分支
        run: |
          git add .  # 将所有文件添加到 git 索引
          git commit -m "自动生成并部署 Jekyll 网站" || echo "No changes to commit"  # 如果没有变化，跳过提交
          git push --force --set-upstream origin gh-pages  # 强制推送到 gh-pages 分支
